name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "AZUREPAT=${{ secrets.AZUREPAT }}" >> $GITHUB_ENV
          echo "AZUSERNAME=${{ secrets.AZUSERNAME }}" >> $GITHUB_ENV

      - name: Run commit.sh
        run: |
          chmod +x commit.sh
          ./commit.sh
